module Mal_step1_read_print

include "./reader"
include "./types"
include "result"
include "string"

let eval = (input) => Ok(input)

let rep = (input) => {
  let output = match (Reader.read_str(input)) {
    Ok(parsed) => match (eval(parsed)) {
      Ok(result) => Types.pr_str(result, true),
      Err(err) => err
    },
    Err(err) => err
  }

  print(output)
}

while(true) {
  rep(Reader.prompt("user> "))
}
